### ISSUE TITLE
编译时出错，请教~

### ISSUE THREAD

**Issue by meijie-jesse** [LeeLulin/esp-homekit-direct#1]
make: Entering directory '/home/jesse/esp-homekit-direct/devices/switch'
CC /home/jesse/esp-homekit-direct/external_libs/wifi_config/src/wifi_config.c
/home/jesse/esp-homekit-direct/external_libs/wifi_config/src/wifi_config.c: In function 'wifi_config_server_on_settings':
/home/jesse/esp-homekit-direct/external_libs/wifi_config/src/wifi_config.c:217:31: error: 'html_settings_header' undeclared (first use in this function)
     client_send_chunk(client, html_settings_header);
                               ^
/home/jesse/esp-homekit-direct/external_libs/wifi_config/src/wifi_config.c:217:31: note: each undeclared identifier is reported only once for each function it appears in
/home/jesse/esp-homekit-direct/external_libs/wifi_config/src/wifi_config.c:220:31: error: 'html_settings_custom_html' undeclared (first use in this function)
  uint8_t buffer_size = strlen(html_settings_custom_html) + strlen(context->custom_html); 
                               ^
/home/jesse/esp-homekit-direct/external_libs/wifi_config/src/wifi_config.c:227:31: error: 'html_settings_body' undeclared (first use in this function)
     client_send_chunk(client, html_settings_body);
                               ^
/home/jesse/esp-homekit-direct/external_libs/wifi_config/src/wifi_config.c:235:17: error: 'html_network_item' undeclared (first use in this function)
                 html_network_item,
                 ^
/home/jesse/esp-homekit-direct/external_libs/wifi_config/src/wifi_config.c:246:31: error: 'html_settings_footer' undeclared (first use in this function)
     client_send_chunk(client, html_settings_footer);
                               ^
/home/jesse/esp-homekit-direct/external_libs/wifi_config/component.mk:8: recipe for target 'build/wifi_config//src/wifi_config.o' failed
make: *** [build/wifi_config//src/wifi_config.o] Error 1
make: Leaving directory '/home/jesse/esp-homekit-direct/devices/switch'

感谢楼主！

**Comment by LeeLulin** [comment]
可能缺文件了 重新clone

**Comment by LeeLulin** [comment]
在使用之前需要先安装esp-open-sdk
具体查看我的博客这篇文章http://leelulin.xyz/2020/03/14/esp-homekit-01/

**Comment by meijie-jesse** [comment]
> 在使用之前需要先安装esp-open-sdk
> 具体查看我的博客这篇文章http://leelulin.xyz/2020/03/14/esp-homekit-01/

感谢您的回复。之前已经配置过了esp-open-sdk，今天按照您的博客教程配置后，依然报错126。网络是全局代理。

make: Entering directory '/home/jesse/Downloads/esp-homekit-direct/devices/switch'
CC /home/jesse/Downloads/esp-homekit-direct/external_libs/wifi_config/src/wifi_config.c
/home/jesse/Downloads/esp-homekit-direct/external_libs/wifi_config/src/wifi_config.c: In function 'wifi_config_server_on_settings':
/home/jesse/Downloads/esp-homekit-direct/external_libs/wifi_config/src/wifi_config.c:217:31: error: 'html_settings_header' undeclared (first use in this function)
     client_send_chunk(client, html_settings_header);
                               ^
/home/jesse/Downloads/esp-homekit-direct/external_libs/wifi_config/src/wifi_config.c:217:31: note: each undeclared identifier is reported only once for each function it appears in
/home/jesse/Downloads/esp-homekit-direct/external_libs/wifi_config/src/wifi_config.c:220:31: error: 'html_settings_custom_html' undeclared (first use in this function)
  uint8_t buffer_size = strlen(html_settings_custom_html) + strlen(context->custom_html); 
                               ^
/home/jesse/Downloads/esp-homekit-direct/external_libs/wifi_config/src/wifi_config.c:227:31: error: 'html_settings_body' undeclared (first use in this function)
     client_send_chunk(client, html_settings_body);
                               ^
/home/jesse/Downloads/esp-homekit-direct/external_libs/wifi_config/src/wifi_config.c:235:17: error: 'html_network_item' undeclared (first use in this function)
                 html_network_item,
                 ^
/home/jesse/Downloads/esp-homekit-direct/external_libs/wifi_config/src/wifi_config.c:246:31: error: 'html_settings_footer' undeclared (first use in this function)
     client_send_chunk(client, html_settings_footer);
                               ^
/home/jesse/Downloads/esp-homekit-direct/external_libs/wifi_config/component.mk:8: recipe for target 'build/wifi_config//src/wifi_config.o' failed
make: *** [build/wifi_config//src/wifi_config.o] Error 1
make: Leaving directory '/home/jesse/Downloads/esp-homekit-direct/devices/switch'

**Comment by LeeLulin** [comment]
有时间我看一下是哪里的问题吧

**Comment by LeeLulin** [comment]
经检查是之前wifi_config这个库同步有问题，我修了一下，自己测试clone + 编译没有问题，你可以试试，非常抱歉耽误你这么长时间

**Comment by meijie-jesse** [comment]
非常感谢您的回复！经过尝试，我编译也通过了，感谢！


我设计了一款三路的继电器开关Spark，可以直接放入86面板中，且已经开源。
当前的接入方式是通过homeassistant桥接到homekit中


现在苦于开发一款直连的homekit固件，您的代码是单路的，我想修改为三路，但因为编程技术太弱，昨晚尝试无果。


如果您有时间且有兴趣的话，不妨修改一下代码，使Spark也能homekit直连。

还望不吝赐教！感谢！


相关资料：
https://github.com/meijie-jesse/Spark-ESP8266-Smart-Device


继电器连接：GPIO12 GPIO13 GPIO16
自复位开关连接:GPIO2 GPIO4 GPIO5





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LeeLulin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月23日(星期四) 晚上6:18
收件人:&nbsp;"LeeLulin/esp-homekit-direct"<esp-homekit-direct@noreply.github.com&gt;;
抄送:&nbsp;"lovejesse@qq.com"<573644657@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [LeeLulin/esp-homekit-direct] 编译时出错，请教~ (#1)





 
经检查是之前wifi_config这个库同步有问题，我修了一下，自己测试clone + 编译没有问题，你可以试试，非常抱歉耽误你这么长时间

**Comment by LeeLulin** [comment]
我目前也在学习，现在仅是将两位作者的代码整合了一下，使它适配esp01s，没有修改太多地方，现在学业繁忙，有时间会研究一下

**Comment by meijie-jesse** [comment]
谢谢！我也是学生，期待以后能有更多的合作~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LeeLulin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月24日(星期五) 中午11:49
收件人:&nbsp;"LeeLulin/esp-homekit-direct"<esp-homekit-direct@noreply.github.com&gt;;
抄送:&nbsp;"lovejesse@qq.com"<573644657@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [LeeLulin/esp-homekit-direct] 编译时出错，请教~ (#1)





 
我目前也在学习，现在仅是将两位作者的代码整合了一下，使它适配esp01s，没有修改太多地方，现在学业繁忙，有时间会研究一下
