### ISSUE TITLE
第一次编译，出现了一些问题，恳请大佬求教

### ISSUE THREAD

**Issue by imashen** [LeeLulin/esp-homekit-direct#2]
![image](https://user-images.githubusercontent.com/50132994/137606299-d7b9ffd8-521c-4f07-b5f4-0a205dd3b532.png)

**Comment by imashen** [comment]
![image](https://user-images.githubusercontent.com/50132994/137606325-7ce82b10-632d-48b1-a7b5-cb6f950f7168.png)

**Comment by imashen** [comment]
上面两个是在docker中运行得到的结果，这个是在宿主机得到的结果
![image](https://user-images.githubusercontent.com/50132994/137606356-51d275ff-be0d-468a-a721-ff25dfb7076d.png)

**Comment by imashen** [comment]
python环境是需要py2还是py3呢，我用了py2

**Comment by imashen** [comment]
make: Entering directory '/opt/esp/esp01-homekit-switch/devices/switch'
CC /opt/esp/esp01-homekit-switch/external_libs/wifi_config/src/wifi_config.c
/opt/esp/esp01-homekit-switch/external_libs/wifi_config/src/wifi_config.c: In function 'wifi_config_server_on_settings':
/opt/esp/esp01-homekit-switch/external_libs/wifi_config/src/wifi_config.c:217:31: error: 'html_settings_header' undeclared (first use in this function)
     client_send_chunk(client, html_settings_header);
                               ^
/opt/esp/esp01-homekit-switch/external_libs/wifi_config/src/wifi_config.c:217:31: note: each undeclared identifier is reported only once for each function it appears in
/opt/esp/esp01-homekit-switch/external_libs/wifi_config/src/wifi_config.c:220:31: error: 'html_settings_custom_html' undeclared (first use in this function)
  uint8_t buffer_size = strlen(html_settings_custom_html) + strlen(context->custom_html); 
                               ^
/opt/esp/esp01-homekit-switch/external_libs/wifi_config/src/wifi_config.c:227:31: error: 'html_settings_body' undeclared (first use in this function)
     client_send_chunk(client, html_settings_body);
                               ^
/opt/esp/esp01-homekit-switch/external_libs/wifi_config/src/wifi_config.c:235:17: error: 'html_network_item' undeclared (first use in this function)
                 html_network_item,
                 ^
/opt/esp/esp01-homekit-switch/external_libs/wifi_config/src/wifi_config.c:246:31: error: 'html_settings_footer' undeclared (first use in this function)
     client_send_chunk(client, html_settings_footer);
                               ^
make: *** [/opt/esp/esp01-homekit-switch/external_libs/wifi_config/component.mk:10: build/wifi_config//src/wifi_config.o] Error 1
make: Leaving directory '/opt/esp/esp01-homekit-switch/devices/switch'

**Comment by imashen** [comment]
更换rtos后解决

**Comment by LeeLulin** [comment]
👍
